### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by s348268281** [inveniosoftware/dictdiffer#140]
```
from dictdiffer import diff, patch, swap, revert

first = {
    "title": "hello",
    "fork_count": 20,
    "stargazers": ["/users/20", "/users/30"],
    "settings": {
        "assignees": [100, 101, 201],
    }
}

second = {
    "title": "hellooo",
    "fork_count": 20,
    "stargazers": ["/users/20", "/users/30", "/users/40"],
    "settings": {
        "assignees": [100, 101, 202],
    }
}

result = diff(second, first)
patched = patch(result, first)
print(patched)
```

```
Traceback (most recent call last):
  File "E:/MyCode/test/test31.py", line 26, in <module>
    patched = patch(result, first)
  File "D:\software\Python3.5.4\lib\site-packages\dictdiffer\__init__.py", line 332, in patch
    patchers[action](node, changes)
  File "D:\software\Python3.5.4\lib\site-packages\dictdiffer\__init__.py", line 323, in remove
    del dest[key]
IndexError: list assignment index out of range
```

**Comment by jirikuncar** [comment]
You should try

```
result = diff(first, second)
```
**or**
```
patched = revert(diff(second, first), first)
```

**Comment by s348268281** [comment]
Ok, thank you. This is my first time, so I'll have to take a closer look at your code.
