### ISSUE TITLE
when dict has unicode keys and ignore parameter is provided exception is raised

### ISSUE THREAD

**Issue by alexsv** [inveniosoftware/dictdiffer#50]
```python
>>> d1 = {u'привет': 1}
>>> d2 = {'hello': 1}
>>> list(diff(d1, d2))
[('add', '', [('hello', 1)]), ('remove', '', [(u'\u043f\u0440\u0438\u0432\u0435\u0442', 1)])]
>>> list(diff(d1, d2, ignore='some'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.virtualenvs/29bc9535-3886-4c57-8727-42160cb6847c/local/lib/python2.7/site-packages/dictdiffer/__init__.py", line 63, in diff
    deletion = [k for k in first if k not in second and check(k)]
  File "/home/alex/.virtualenvs/29bc9535-3886-4c57-8727-42160cb6847c/local/lib/python2.7/site-packages/dictdiffer/__init__.py", line 59, in check
    else '.'.join(node + [str(key)])) not in ignore
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

**Comment by jirikuncar** [comment]
@alexsv can you please review hotfix in #51? Thanks
