### ISSUE TITLE
dictdiffer breaks if dict contains numpy arrays

### ISSUE THREAD

**Issue by kmuehlbauer** [inveniosoftware/dictdiffer#68]
When comparing two nested dictionaries containing numpy arrays it breaks with the well known:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
To reproduce:

```
import numpy as np
from dictdiffer import diff

d1 = {'a': np.array([1, 2, 3])}
d2 = {'a': np.array([1, 2, 4])}

print(list(diff(d1,d2)))
```
Traceback:

```
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    print(list(diff(d1,d2)))
  File "/local/kai/anaconda/lib/python2.7/site-packages/dictdiffer/__init__.py", line 150, in diff
    for diffed in recurred:
  File "/local/kai/anaconda/lib/python2.7/site-packages/dictdiffer/__init__.py", line 205, in diff
    if are_different(first, second, tolerance):
  File "/local/kai/anaconda/lib/python2.7/site-packages/dictdiffer/utils.py", line 264, in are_different
    if first == second:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Unfortunately I have no elegant solution to this, but changing `are_different` like this works for my specific use case:

```
    # only check if same type
    if type(first) == type(second):
        # check if ndarray type
        if 'ndarray' in str(type(first)):
            return not (first == second).all()
        if first == second:
            # values are same - simple case
            return False
        elif bool(first != first) ^ bool(second != second):
            # only one of them is 'NaN', hence they are different
            return True
        elif isinstance(first, num_types) and isinstance(second, num_types):
            # (a) two numerical values are compared with tolerance
            # (b) both values are NaN and they will never fit the tolerance
            return abs(first-second) > tolerance * max(abs(first), abs(second))
    # we got different values
    return True
```

**Comment by jirikuncar** [comment]
@kmuehlbauer fixing `are_different` is only first step if you want to know that two `np.array`s are different. However, we would need to add `np.array` to `LIST_TYPE` to detect changes, otherwise you would get result as:

```diff
diff --git a/dictdiffer/utils.py b/dictdiffer/utils.py
index e830e83..0f62dab 100644
--- a/dictdiffer/utils.py
+++ b/dictdiffer/utils.py
@@ -258,7 +258,11 @@ def are_different(first, second, tolerance):
     are different.
     In all other cases, the difference is straight forward.
     """
-    if first == second:
+    result = first == second
+    if not hasattr(result, '__bool__') and hasattr(result, 'all'):
+        # support for Numpy arrays
+        return not result.all()
+    elif result:
         # values are same - simple case
         return False
     elif bool(first != first) ^ bool(second != second):
diff --git a/tests/test_dictdiffer.py b/tests/test_dictdiffer.py
index b987eb3..428b8d3 100644
--- a/tests/test_dictdiffer.py
+++ b/tests/test_dictdiffer.py
@@ -336,6 +336,14 @@ class DictDifferTests(unittest.TestCase):
         first = {1: [1]}
         assert len(list(diff(first, first))) == 0
 
+    def test_numpy_array(self):
+        import numpy as np
+        first = np.array([1, 2, 3])
+        second = np.array([1, 2, 4])
+        result = list(diff(first, second))
+        assert result == [('change', '', (np.array([1, 2, 3]),
+                                          np.array([1, 2, 4]))]
+
     def test_dict_subclasses(self):
         class Foo(dict):
             pass
```
